version: '3'
services:
  webserver:
    image: nginx
    ports:
      - '8000-8010:80' #Ports 8000 to 8010 will be redirected from 80 while using scaling
    volumes:
      - /var/lib/docker/volumes/volume01:/root/volume/
    networks:
      - network01
  dbserver:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
     - network01
networks:
  network01:
